def swipeFileData():
    fileInput1=input("Enter the 1st file to swap")
    fileInput2=input("Enter the 2nd file to swap")
    print(fileInput1)
    print(fileInput2)
    file1=open(fileInput1, "r")
    data_a=file1.read()
    file2=open(fileInput2, "r")   
    data_b=file2.read()
    print(data_a)
    print(data_b)
    file1=open(fileInput1, "w")
    file2=open(fileInput2, "w")
    file1.write(data_b)
    file2.write(data_a)
swipeFileData()
